apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresUser | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresPassword | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresDb | quote }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
